-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text,
  url text,
  rating VARCHAR(5)
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, rating)
values
  ('Google', 'http://www.google.com', 4),
	('Google1', 'http://www.google.com', 5),
	('Google2', 'http://www.google.com', 3)


 